name: Auto-Fix PR Review Comments with OpenHands

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Check required environment variables
        env:
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
        run: |
          required_vars=("LLM_MODEL" "LLM_API_KEY" "PAT_TOKEN" "PAT_USERNAME")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: Required environment variable $var is not set."
              exit 1
            fi
          done

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Kiwano-ai/openhands-resolver.git

      - name: Attempt to resolve review comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
        run: |
          python -m openhands_resolver.resolve_pr_review \
            --repo ${{ github.repository }} \
            --pr-number ${{ github.event.pull_request.number }} \
            --review-id ${{ github.event.review.id }}

      - name: Check resolution result
        id: check_result
        run: |
          if grep -q '"success":true' output/output.jsonl; then
            echo "RESOLUTION_SUCCESS=true" >> $GITHUB_OUTPUT
          else
            echo "RESOLUTION_SUCCESS=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_result.outputs.RESOLUTION_SUCCESS == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-fix: Addressing PR review comments"
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const success = ${{ steps.check_result.outputs.RESOLUTION_SUCCESS }};
            const prNumber = ${{ github.event.pull_request.number }};
            
            if (success) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `OpenHands has attempted to address the review comments. Please check the latest commit for the changes.`
              });
            } else {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `OpenHands attempted to address the review comments but was unsuccessful. Manual intervention may be required.`
              });
            }
